name: firebase_pet_social
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase (versiones compatibles entre sí)
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.2
  firebase_database: ^10.3.9
  firebase_storage: ^11.2.7

  # Otros
  cached_network_image: ^3.4.0
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets (imágenes, iconos, etc)
  assets:
    - assets/images/
    - web/icons/pawgram.png
